import React, { useEffect, useMemo, useState } from 'react';
import { toast } from 'sonner';
import pb from '@/lib/pocketbaseClient';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { EXPENSE_CATEGORIES, formatBRL, invoiceMonthForPurchase, parseAmount, todayInput } from '@/lib/finance';

export default function CardPurchaseDialog({ open, onOpenChange, cards, cardId, onSaved }) {
  const [selectedCard, setSelectedCard] = useState(cardId || ''); const [description, setDescription] = useState(''); const [amount, setAmount] = useState(''); const [category, setCategory] = useState('outros'); const [date, setDate] = useState(todayInput()); const [installments, setInstallments] = useState('1'); const [notes, setNotes] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(()=>{ if(open){ setSelectedCard(cardId || cards?.[0]?.id || ''); setDescription(''); setAmount(''); setCategory('outros'); setDate(todayInput()); setInstallments('1'); setNotes(''); } },[open,cardId,cards]);
  const card = cards.find(c=>c.id===selectedCard);
  const installmentValue = useMemo(()=>{ const n=parseAmount(amount); const i=Math.max(1,Number(installments)||1); return Number.isFinite(n)?n/i:0; },[amount,installments]);
  const firstInvoice = card && date ? invoiceMonthForPurchase(date, card.closing_day) : '';
  const submit=async(e)=>{e.preventDefault(); if(card?.card_type && card.card_type!=='credito') return toast.error('Parcelamento é exclusivo para cartão de crédito.'); const numeric=parseAmount(amount); const count=Number(installments); if(!selectedCard||!description.trim()||!Number.isFinite(numeric)||numeric<=0||!Number.isInteger(count)||count<1||count>60)return toast.error('Preencha os dados da compra corretamente.'); setSaving(true); try { const rec=await pb.collection('card_purchases').create({card_id:selectedCard,description:description.trim(),amount:numeric,category,purchase_date:date,installments:count,notes:notes.trim()}); onSaved(rec); onOpenChange(false); toast.success('Compra adicionada à fatura.'); } catch(err){console.error(err);toast.error('Não foi possível salvar a compra.');} finally{setSaving(false);} };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>Nova compra no cartão</DialogTitle><DialogDescription>A compra entra na fatura e já compromete o limite.</DialogDescription></DialogHeader><form onSubmit={submit} className="mt-5 space-y-4"><div className="space-y-2"><Label>Cartão</Label><Select value={selectedCard} onValueChange={setSelectedCard}><SelectTrigger><SelectValue placeholder="Selecione o cartão"/></SelectTrigger><SelectContent>{cards.map(c=><SelectItem key={c.id} value={c.id}>{c.name} · {c.bank}</SelectItem>)}</SelectContent></Select></div><div className="space-y-2"><Label>Descrição</Label><Input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Ex.: Mercado" required/></div><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>Valor total</Label><Input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0,00" required/></div><div className="space-y-2"><Label>Categoria</Label><Select value={category} onValueChange={setCategory}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{EXPENSE_CATEGORIES.map(c=><SelectItem key={c.value} value={c.value}>{c.label}</SelectItem>)}</SelectContent></Select></div></div><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>Data da compra</Label><Input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></div><div className="space-y-2"><Label>Parcelas</Label><Input type="number" min="1" max="60" value={installments} onChange={e=>setInstallments(e.target.value)} required/></div></div><div className="rounded-lg bg-muted p-3 text-sm">{card ? <><p>1ª fatura: <strong>{firstInvoice}</strong></p><p className="mt-1">Parcela estimada: <strong>{formatBRL(installmentValue)}</strong></p></> : <p>Selecione um cartão.</p>}</div><div className="space-y-2"><Label>Observação (opcional)</Label><Input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Detalhes adicionais"/></div><DialogFooter><Button type="button" variant="outline" onClick={()=>onOpenChange(false)}>Cancelar</Button><Button type="submit" disabled={saving||cards.length===0}>{saving?'Salvando…':'Adicionar compra'}</Button></DialogFooter></form></DialogContent></Dialog>;
}
