import React, { useEffect, useState } from 'react';
import { toast } from 'sonner';
import pb from '@/lib/pocketbaseClient';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { parseAmount } from '@/lib/finance';

export default function CreditCardDialog({ open, onOpenChange, card, onSaved }) {
  const [name, setName] = useState(''); const [bank, setBank] = useState(''); const [limit, setLimit] = useState(''); const [closing, setClosing] = useState('10'); const [due, setDue] = useState('17'); const [saving, setSaving] = useState(false);
  useEffect(() => { if (card) { setName(card.name || ''); setBank(card.bank || ''); setLimit(String(card.credit_limit ?? '').replace('.', ',')); setClosing(String(card.closing_day ?? 10)); setDue(String(card.due_day ?? 17)); } else { setName(''); setBank(''); setLimit(''); setClosing('10'); setDue('17'); } }, [card, open]);
  const submit = async (e) => { e.preventDefault(); const numeric = parseAmount(limit); if (!name.trim() || !bank.trim() || !Number.isFinite(numeric) || numeric <= 0) return toast.error('Preencha banco, cartão e um limite válido.'); setSaving(true); try { const payload={name:name.trim(),bank:bank.trim(),credit_limit:numeric,closing_day:Number(closing),due_day:Number(due)}; const rec=card ? await pb.collection('credit_cards').update(card.id,payload) : await pb.collection('credit_cards').create(payload); onSaved(rec); onOpenChange(false); toast.success(card ? 'Cartão atualizado.' : 'Cartão adicionado.'); } catch(err){ console.error(err); toast.error('Não foi possível salvar o cartão.'); } finally { setSaving(false); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{card ? 'Editar cartão' : 'Adicionar cartão'}</DialogTitle><DialogDescription>Cadastre o limite e o ciclo da sua fatura.</DialogDescription></DialogHeader><form onSubmit={submit} className="mt-5 space-y-4"><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>Nome do cartão</Label><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Nubank" required/></div><div className="space-y-2"><Label>Banco</Label><Input value={bank} onChange={e=>setBank(e.target.value)} placeholder="Ex.: Nubank" required/></div></div><div className="space-y-2"><Label>Limite</Label><Input inputMode="decimal" value={limit} onChange={e=>setLimit(e.target.value)} placeholder="1.000,00" required/></div><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>Fechamento</Label><Input type="number" min="1" max="31" value={closing} onChange={e=>setClosing(e.target.value)} required/></div><div className="space-y-2"><Label>Vencimento</Label><Input type="number" min="1" max="31" value={due} onChange={e=>setDue(e.target.value)} required/></div></div><p className="text-xs text-muted-foreground">Compras após o dia de fechamento entram na próxima fatura.</p><DialogFooter><Button type="button" variant="outline" onClick={()=>onOpenChange(false)}>Cancelar</Button><Button type="submit" disabled={saving}>{saving?'Salvando…':'Salvar cartão'}</Button></DialogFooter></form></DialogContent></Dialog>;
}
