import React, { useEffect, useState } from 'react';
import { toast } from 'sonner';
import pb from '@/lib/pocketbaseClient';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { ASSET_TYPES, parseAmount, todayInput } from '@/lib/finance';

export default function InvestmentDialog({ open, onOpenChange, investment, onSaved }) {
  const [asset,setAsset]=useState(''); const [assetType,setAssetType]=useState('acao'); const [quantity,setQuantity]=useState(''); const [avgPrice,setAvgPrice]=useState(''); const [currentPrice,setCurrentPrice]=useState(''); const [purchaseDate,setPurchaseDate]=useState(todayInput()); const [saving,setSaving]=useState(false);
  useEffect(()=>{if(investment){setAsset(investment.asset||'');setAssetType(investment.assetType||'acao');setQuantity(String(investment.quantity??''));setAvgPrice(String(investment.avgPrice??'').replace('.',','));setCurrentPrice(String(investment.currentPrice??'').replace('.',','));setPurchaseDate(investment.purchaseDate||todayInput());}else{setAsset('');setAssetType('acao');setQuantity('');setAvgPrice('');setCurrentPrice('');setPurchaseDate(todayInput());}},[investment,open]);
  const submit=async(e)=>{e.preventDefault();const q=parseAmount(quantity),avg=parseAmount(avgPrice),cur=currentPrice===''?0:parseAmount(currentPrice);if(!asset.trim()||!Number.isFinite(q)||q<=0||!Number.isFinite(avg)||avg<0||!Number.isFinite(cur)||cur<0)return toast.error('Preencha os campos com valores válidos.');setSaving(true);try{const payload={asset:asset.trim().toUpperCase(),assetType,quantity:q,avgPrice:avg,currentPrice:cur,purchaseDate};const rec=investment?await pb.collection('investments').update(investment.id,payload):await pb.collection('investments').create(payload);onSaved(rec);onOpenChange(false);toast.success(investment?'Posição atualizada.':'Investimento adicionado.');}catch(err){console.error(err);toast.error('Não foi possível salvar o investimento.');}finally{setSaving(false)}};
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{investment?'Editar investimento':'Nova posição'}</DialogTitle><DialogDescription>Registre a quantidade, preço médio e o último preço que você deseja acompanhar.</DialogDescription></DialogHeader><form onSubmit={submit} className="mt-5 space-y-4"><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>Ativo</Label><Input value={asset} onChange={e=>setAsset(e.target.value)} placeholder="PETR4" required/></div><div className="space-y-2"><Label>Tipo</Label><Select value={assetType} onValueChange={setAssetType}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{ASSET_TYPES.map(t=><SelectItem key={t.value} value={t.value}>{t.label}</SelectItem>)}</SelectContent></Select></div></div><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>Quantidade</Label><Input inputMode="decimal" value={quantity} onChange={e=>setQuantity(e.target.value)} placeholder="10" required/></div><div className="space-y-2"><Label>Preço médio</Label><Input inputMode="decimal" value={avgPrice} onChange={e=>setAvgPrice(e.target.value)} placeholder="35,50" required/></div></div><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>Preço atual</Label><Input inputMode="decimal" value={currentPrice} onChange={e=>setCurrentPrice(e.target.value)} placeholder="Opcional"/></div><div className="space-y-2"><Label>Data da compra</Label><Input type="date" value={purchaseDate} onChange={e=>setPurchaseDate(e.target.value)} required/></div></div><DialogFooter><Button type="button" variant="outline" onClick={()=>onOpenChange(false)}>Cancelar</Button><Button type="submit" disabled={saving}>{saving?'Salvando…':'Salvar'}</Button></DialogFooter></form></DialogContent></Dialog>;
}
