import React, { useEffect, useState } from 'react';
import { toast } from 'sonner';
import pb from '@/lib/pocketbaseClient';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { EXPENSE_CATEGORIES, INCOME_CATEGORIES, parseAmount, todayInput } from '@/lib/finance';

export default function TransactionDialog({ open, onOpenChange, transaction, onSaved }) {
  const [type, setType] = useState('entrada'); const [description, setDescription] = useState(''); const [amount, setAmount] = useState(''); const [category, setCategory] = useState('outros'); const [date, setDate] = useState(todayInput()); const [notes, setNotes] = useState(''); const [saving, setSaving] = useState(false);
  useEffect(() => { if (transaction) { setType(transaction.type); setDescription(transaction.description || ''); setAmount(String(transaction.amount ?? '').replace('.', ',')); setCategory(transaction.category || 'outros'); setDate(transaction.date || todayInput()); setNotes(transaction.notes || ''); } else { setType('entrada'); setDescription(''); setAmount(''); setCategory('outros'); setDate(todayInput()); setNotes(''); } }, [transaction, open]);
  const categories = type === 'entrada' ? INCOME_CATEGORIES : EXPENSE_CATEGORIES;
  const submit = async (e) => { e.preventDefault(); const numeric = parseAmount(amount); if (!description.trim() || !Number.isFinite(numeric) || numeric <= 0) return toast.error('Informe descrição e um valor válido.'); setSaving(true); try { const payload={type,description:description.trim(),amount:numeric,category,date,notes:notes.trim()}; const rec=transaction ? await pb.collection('transactions').update(transaction.id,payload) : await pb.collection('transactions').create(payload); onSaved(rec); onOpenChange(false); toast.success(transaction ? 'Transação atualizada.' : 'Transação adicionada.'); } catch (err) { console.error(err); toast.error('Não foi possível salvar a transação.'); } finally { setSaving(false); } };
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{transaction ? 'Editar transação' : 'Nova transação'}</DialogTitle><DialogDescription>Registre uma entrada ou saída da sua carteira.</DialogDescription></DialogHeader><form onSubmit={submit} className="mt-5 space-y-4"><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>Tipo</Label><Select value={type} onValueChange={(v)=>{setType(v);setCategory('outros')}}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent><SelectItem value="entrada">Entrada</SelectItem><SelectItem value="saida">Saída</SelectItem></SelectContent></Select></div><div className="space-y-2"><Label>Data</Label><Input type="date" value={date} onChange={e=>setDate(e.target.value)} required/></div></div><div className="space-y-2"><Label>Descrição</Label><Input value={description} onChange={e=>setDescription(e.target.value)} placeholder="Ex.: Salário" required/></div><div className="grid grid-cols-2 gap-3"><div className="space-y-2"><Label>Valor</Label><Input inputMode="decimal" value={amount} onChange={e=>setAmount(e.target.value)} placeholder="0,00" required/></div><div className="space-y-2"><Label>Categoria</Label><Select value={category} onValueChange={setCategory}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{categories.map(c=><SelectItem key={c.value} value={c.value}>{c.label}</SelectItem>)}</SelectContent></Select></div></div><div className="space-y-2"><Label>Observação (opcional)</Label><Input value={notes} onChange={e=>setNotes(e.target.value)} placeholder="Detalhes adicionais"/></div><DialogFooter><Button type="button" variant="outline" onClick={()=>onOpenChange(false)}>Cancelar</Button><Button type="submit" disabled={saving}>{saving?'Salvando…':'Salvar'}</Button></DialogFooter></form></DialogContent></Dialog>;
}
