import * as React from 'react';
import * as DialogPrimitive from '@radix-ui/react-dialog';
import { X } from 'lucide-react';
import { cn } from '@/lib/utils';
export const Dialog = DialogPrimitive.Root;
export const DialogTrigger = DialogPrimitive.Trigger;
export const DialogPortal = DialogPrimitive.Portal;
export const DialogClose = DialogPrimitive.Close;
export const DialogOverlay = React.forwardRef(({className,...props},ref)=><DialogPrimitive.Overlay ref={ref} className={cn('fixed inset-0 z-50 bg-black/50 backdrop-blur-sm data-[state=open]:animate-in data-[state=closed]:animate-out',className)} {...props}/>);
DialogOverlay.displayName='DialogOverlay';
export const DialogContent = React.forwardRef(({className,children,...props},ref)=><DialogPortal><DialogOverlay/><DialogPrimitive.Content ref={ref} className={cn('fixed left-1/2 top-1/2 z-50 w-[calc(100%-2rem)] max-w-lg -translate-x-1/2 -translate-y-1/2 rounded-xl border border-border bg-card p-6 shadow-xl',className)} {...props}>{children}<DialogPrimitive.Close className="absolute right-4 top-4 rounded-sm p-1 text-muted-foreground hover:bg-muted hover:text-foreground"><X className="h-4 w-4"/><span className="sr-only">Fechar</span></DialogPrimitive.Close></DialogPrimitive.Content></DialogPortal>);
DialogContent.displayName='DialogContent';
export const DialogHeader=({className,...props})=><div className={cn('flex flex-col space-y-1.5',className)} {...props}/>;
export const DialogFooter=({className,...props})=><div className={cn('flex flex-col-reverse gap-2 sm:flex-row sm:justify-end',className)} {...props}/>;
export const DialogTitle=React.forwardRef(({className,...props},ref)=><DialogPrimitive.Title ref={ref} className={cn('text-lg font-semibold',className)} {...props}/>);
export const DialogDescription=React.forwardRef(({className,...props},ref)=><DialogPrimitive.Description ref={ref} className={cn('text-sm text-muted-foreground',className)} {...props}/>);
