import React, { useEffect, useMemo, useState } from 'react';
import { Plus, Pencil, Trash2, Wallet } from 'lucide-react';
import { toast } from 'sonner';
import pb from '@/lib/pocketbaseClient';
import Reveal from '@/components/Reveal';
import { Button } from '@/components/ui/button';
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from '@/components/ui/dialog';
import { Input } from '@/components/ui/input';
import { Label } from '@/components/ui/label';
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select';
import { formatBRL, parseAmount } from '@/lib/finance';

export default function AccountsPage(){
  const [accounts,setAccounts]=useState([]); const [transactions,setTransactions]=useState([]); const [open,setOpen]=useState(false); const [editing,setEditing]=useState(null);
  const load=async()=>{const [a,t]=await Promise.all([pb.collection('accounts').getFullList({sort:'name'}),pb.collection('transactions').getFullList({sort:'-date'})]);setAccounts(a);setTransactions(t)};
  useEffect(()=>{load().catch(e=>{console.error(e);toast.error('Não foi possível carregar as contas.')})},[]);
  const balances=useMemo(()=>accounts.map(a=>{let value=Number(a.initial_balance||0);transactions.filter(t=>t.account_id===a.id || (!t.account_id && t.payment_method==='conta')).forEach(t=>{value+=(t.type==='entrada'?1:-1)*Number(t.amount||0)});return {...a,balance:value}}),[accounts,transactions]);
  const save=async(payload)=>{try{const rec=editing?await pb.collection('accounts').update(editing.id,payload):await pb.collection('accounts').create(payload);setAccounts(p=>editing?p.map(x=>x.id===rec.id?rec:x):[...p,rec].sort((a,b)=>a.name.localeCompare(b.name)));setOpen(false);setEditing(null);toast.success(editing?'Conta atualizada.':'Conta adicionada.')}catch(e){console.error(e);toast.error('Não foi possível salvar a conta.')}};
  const remove=async(a)=>{if(!confirm(`Excluir a conta ${a.name}?`))return;try{await pb.collection('accounts').delete(a.id);setAccounts(p=>p.filter(x=>x.id!==a.id));toast.success('Conta excluída.')}catch(e){toast.error('Não foi possível excluir a conta.')}};
  return <div><Reveal><header className="mb-8 flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium uppercase tracking-widest text-muted-foreground">Dinheiro real</p><h1 className="mt-1 text-4xl font-bold tracking-tight">Contas <span className="font-serif italic font-medium">e saldos</span></h1></div><Button onClick={()=>{setEditing(null);setOpen(true)}} className="bg-accent text-accent-foreground"><Plus className="mr-2 h-4 w-4"/>Nova conta</Button></header></Reveal>
  <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-3">{balances.map(a=><Reveal key={a.id}><div className="rounded-xl border border-border bg-card p-5"><div className="flex items-start justify-between"><div className="flex items-center gap-3"><div className="rounded-lg bg-primary p-2 text-primary-foreground"><Wallet className="h-4 w-4"/></div><div><h2 className="font-semibold">{a.name}</h2><p className="text-xs text-muted-foreground">{a.type==='corrente'?'Conta corrente':a.type==='poupanca'?'Poupança':'Dinheiro'}</p></div></div><div className="flex gap-1"><Button size="icon" variant="ghost" onClick={()=>{setEditing(a);setOpen(true)}}><Pencil className="h-4 w-4"/></Button><Button size="icon" variant="ghost" onClick={()=>remove(a)}><Trash2 className="h-4 w-4"/></Button></div></div><p className="mt-6 text-3xl font-bold">{formatBRL(a.balance)}</p></div></Reveal>)}{balances.length===0&&<div className="rounded-xl border border-dashed p-10 text-center text-sm text-muted-foreground md:col-span-2 lg:col-span-3">Cadastre sua primeira conta para acompanhar o dinheiro disponível.</div>}</div>
  <AccountDialog open={open} onOpenChange={v=>{setOpen(v);if(!v)setEditing(null)}} account={editing} onSave={save}/></div>
}
function AccountDialog({open,onOpenChange,account,onSave}){const [name,setName]=useState('');const[type,setType]=useState('corrente');const[balance,setBalance]=useState('');useEffect(()=>{if(open){setName(account?.name||'');setType(account?.type||'corrente');setBalance(String(account?.initial_balance??'').replace('.',','))}},[open,account]);return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent><DialogHeader><DialogTitle>{account?'Editar conta':'Nova conta'}</DialogTitle><DialogDescription>O saldo inicial é usado como ponto de partida; as transações vinculadas alteram o saldo.</DialogDescription></DialogHeader><div className="space-y-4"><div><Label>Nome</Label><Input value={name} onChange={e=>setName(e.target.value)} placeholder="Ex.: Nubank"/></div><div><Label>Tipo</Label><Select value={type} onValueChange={setType}><SelectTrigger/><SelectContent><SelectItem value="corrente">Conta corrente</SelectItem><SelectItem value="poupanca">Poupança</SelectItem><SelectItem value="dinheiro">Dinheiro</SelectItem></SelectContent></Select></div><div><Label>Saldo inicial</Label><Input inputMode="decimal" value={balance} onChange={e=>setBalance(e.target.value)} placeholder="0,00"/></div></div><DialogFooter><Button variant="outline" onClick={()=>onOpenChange(false)}>Cancelar</Button><Button onClick={()=>{const n=parseAmount(balance);if(!name.trim()||!Number.isFinite(n))return toast.error('Preencha nome e saldo.');onSave({name:name.trim(),type,initial_balance:n})}}>Salvar</Button></DialogFooter></DialogContent></Dialog>}
